project:
  type: website

website:
  title: "Begin R"
  sidebar:
    style: "floating"
    search: false
    contents:
      - text: "1. R starts here!"
        href: index.qmd
      - text: "2. Vectors and variables"
        href: vectors-and-variables.qmd
      - text: "3. Data files and data frames"
        href: data-files-and-data-frames.qmd
      - text: "4. Visualization"
        href: visualization.qmd
      - text: "5. And all the rest"
        href: and-all-the-rest.qmd
      - text: "---"
      - text: "R playground"
        href: playground.qmd
      - text: "About"
        href: about.qmd
  body-header: |
    <div style="text-align: right;">
      <button id="reset-exercise-button" style="border-width: 0px; text-decoration: underline;">
        Restart chapter
      </button>
    </div>
  page-footer: 
    left:  "Made by [Rasmus Bååth](https://www.sumsar.net)" 
  
format: 
  live-html:
    webr:
      packages:
        - base
      cell-options:
        persist: true
        caption: 
        warning: false
    theme: cosmo
    css: styles.css
    toc: false
    include-in-header:
      - quarto-live-customization.html
          
output_dir: _site
engine: knitr